<a href="https://colab.research.google.com/github/lakkireddylahari-bot/panda/blob/main/panda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df = pd.read_excel("/content/drive/MyDrive/datasets for data science.bytexl/student_dataset_20rows.xlsx")
print(df)

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [67]:
# selecting rows using iloc function
# iloc = integer location
df.iloc[0]

Student_ID           101
Name                 Ram
Age                   25
Course            Pandas
Marks                 90
City          Vijayawada
Name: 0, dtype: object

In [11]:
# selecting colums
df.columns

Index(['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'City'], dtype='object')

In [12]:
df

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [3]:
# selecting specific rows and columns
# df.iloc[rowselection, columnselection]
df.iloc[0:3, 0:3]

   Student_ID  Name  Age
0         101   Ram   25
1         102  Ravi   23
2         103  Sita   21

In [5]:
df.iloc[0,0:3]

Student_ID    101
Name          Ram
Age            25
Name: 0, dtype: object

In [68]:
df.iloc[[0,1]]

   Student_ID  Name  Age  Course  Marks        City
0         101   Ram   25  Pandas     90  Vijayawada
1         102  Ravi   23   NumPy     81   Hyderabad

In [14]:
df.iloc[:, 1]

0         Ram
1        Ravi
2        Sita
3       Kiran
4         Anu
5       Rahul
6       Sneha
7       Arjun
8       Pooja
9      Vikram
10      Divya
11       Ajay
12    Keerthi
13     Nikhil
14      Meena
15        Sai
16    Lavanya
17      Rohit
18       Teja
19      Priya
Name: Name, dtype: object

In [15]:
df.loc[0:2]

   Student_ID  Name  Age  Course  Marks        City
0         101   Ram   25  Pandas     90  Vijayawada
1         102  Ravi   23   NumPy     81   Hyderabad
2         103  Sita   21  Python     80     Chennai

In [17]:
df.loc[:, "Name"]

0         Ram
1        Ravi
2        Sita
3       Kiran
4         Anu
5       Rahul
6       Sneha
7       Arjun
8       Pooja
9      Vikram
10      Divya
11       Ajay
12    Keerthi
13     Nikhil
14      Meena
15        Sai
16    Lavanya
17      Rohit
18       Teja
19      Priya
Name: Name, dtype: object

In [19]:
df.loc[:,["Name", "Age", "City"]]

       Name  Age         City
0       Ram   25   Vijayawada
1      Ravi   23    Hyderabad
2      Sita   21      Chennai
3     Kiran   21    Bangalore
4       Anu   20       Mumbai
5     Rahul   22        Delhi
6     Sneha   25         Pune
7     Arjun   22      Kolkata
8     Pooja   20        Vizag
9    Vikram   20     Tirupati
10    Divya   23     Warangal
11     Ajay   21       Guntur
12  Keerthi   21      Nellore
13   Nikhil   22       Kadapa
14    Meena   23      Kurnool
15      Sai   25       Ongole
16  Lavanya   20  Rajahmundry
17    Rohit   23        Eluru
18     Teja   25      Khammam
19    Priya   22    Nizamabad

In [20]:
df.loc[5:8, ["Name", "Age", "City"]]

    Name  Age     City
5  Rahul   22    Delhi
6  Sneha   25     Pune
7  Arjun   22  Kolkata
8  Pooja   20    Vizag

In [22]:
# tasks
df.iloc[:, 1]

0         Ram
1        Ravi
2        Sita
3       Kiran
4         Anu
5       Rahul
6       Sneha
7       Arjun
8       Pooja
9      Vikram
10      Divya
11       Ajay
12    Keerthi
13     Nikhil
14      Meena
15        Sai
16    Lavanya
17      Rohit
18       Teja
19      Priya
Name: Name, dtype: object

In [24]:
df.loc[:, "Name"]

0         Ram
1        Ravi
2        Sita
3       Kiran
4         Anu
5       Rahul
6       Sneha
7       Arjun
8       Pooja
9      Vikram
10      Divya
11       Ajay
12    Keerthi
13     Nikhil
14      Meena
15        Sai
16    Lavanya
17      Rohit
18       Teja
19      Priya
Name: Name, dtype: object

In [25]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'City'], dtype='object')

In [27]:
df.loc[:, ["Name", "City"]]

       Name         City
0       Ram   Vijayawada
1      Ravi    Hyderabad
2      Sita      Chennai
3     Kiran    Bangalore
4       Anu       Mumbai
5     Rahul        Delhi
6     Sneha         Pune
7     Arjun      Kolkata
8     Pooja        Vizag
9    Vikram     Tirupati
10    Divya     Warangal
11     Ajay       Guntur
12  Keerthi      Nellore
13   Nikhil       Kadapa
14    Meena      Kurnool
15      Sai       Ongole
16  Lavanya  Rajahmundry
17    Rohit        Eluru
18     Teja      Khammam
19    Priya    Nizamabad

In [30]:
df.loc[:, ["Name", "City"]]

       Name         City
0       Ram   Vijayawada
1      Ravi    Hyderabad
2      Sita      Chennai
3     Kiran    Bangalore
4       Anu       Mumbai
5     Rahul        Delhi
6     Sneha         Pune
7     Arjun      Kolkata
8     Pooja        Vizag
9    Vikram     Tirupati
10    Divya     Warangal
11     Ajay       Guntur
12  Keerthi      Nellore
13   Nikhil       Kadapa
14    Meena      Kurnool
15      Sai       Ongole
16  Lavanya  Rajahmundry
17    Rohit        Eluru
18     Teja      Khammam
19    Priya    Nizamabad

In [32]:
df[['Name', 'City']]

       Name         City
0       Ram   Vijayawada
1      Ravi    Hyderabad
2      Sita      Chennai
3     Kiran    Bangalore
4       Anu       Mumbai
5     Rahul        Delhi
6     Sneha         Pune
7     Arjun      Kolkata
8     Pooja        Vizag
9    Vikram     Tirupati
10    Divya     Warangal
11     Ajay       Guntur
12  Keerthi      Nellore
13   Nikhil       Kadapa
14    Meena      Kurnool
15      Sai       Ongole
16  Lavanya  Rajahmundry
17    Rohit        Eluru
18     Teja      Khammam
19    Priya    Nizamabad

In [36]:
df.iloc[[0,1,2], :]

   Student_ID  Name  Age  Course  Marks        City
0         101   Ram   25  Pandas     90  Vijayawada
1         102  Ravi   23   NumPy     81   Hyderabad
2         103  Sita   21  Python     80     Chennai

In [37]:
df.loc[[0,1,2], :]

   Student_ID  Name  Age  Course  Marks        City
0         101   Ram   25  Pandas     90  Vijayawada
1         102  Ravi   23   NumPy     81   Hyderabad
2         103  Sita   21  Python     80     Chennai

In [47]:
df.iloc[0:2,0:2]

   Student_ID  Name
0         101   Ram
1         102  Ravi

In [51]:
df.loc[0:1,["Student_ID","Name"]]

   Student_ID  Name
0         101   Ram
1         102  Ravi

In [52]:
print(df.loc[:, "Marks"])

0     90
1     81
2     80
3     98
4     70
5     82
6     79
7     70
8     95
9     72
10    94
11    84
12    74
13    99
14    81
15    97
16    72
17    70
18    90
19    78
Name: Marks, dtype: int64

In [63]:
df.iloc[:,4]

0     90
1     81
2     80
3     98
4     70
5     82
6     79
7     70
8     95
9     72
10    94
11    84
12    74
13    99
14    81
15    97
16    72
17    70
18    90
19    78
Name: Marks, dtype: int64

In [69]:
# filtering marks greater than 80
df[df["Marks"]>80]

    Student_ID    Name  Age            Course  Marks        City
0          101     Ram   25            Pandas     90  Vijayawada
1          102    Ravi   23             NumPy     81   Hyderabad
3          104   Kiran   21      Data Science     98   Bangalore
5          106   Rahul   22               SQL     82       Delhi
8          109   Pooja   20            Python     95       Vizag
10         111   Divya   23     Deep Learning     94    Warangal
11         112    Ajay   21            Python     84      Guntur
13         114  Nikhil   22     Deep Learning     99      Kadapa
14         115   Meena   23                AI     81     Kurnool
15         116     Sai   25            Pandas     97      Ongole
18         119    Teja   25  Machine Learning     90     Khammam

In [71]:
df[df["Marks"]<70]

Empty DataFrame
Columns: [Student_ID, Name, Age, Course, Marks, City]
Index: []

In [77]:
df[df["City"] == "Bangalore"]

   Student_ID   Name  Age        Course  Marks       City
3         104  Kiran   21  Data Science     98  Bangalore

In [78]:
df[df["Age"] < 30]

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [82]:
df[(df["Marks"]>25)|(df["Age"]<30)]

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [83]:
df.loc[df["City"]=="Chennai" , ["Name", "Age"]]

   Name  Age
2  Sita   21

In [84]:
import seaborn as sns
df = sns.load_dataset('titanic')
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [85]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True